name: artifacts-upload

on:
  push:
    branches:
     - main

jobs:
  artifacts-upload:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo for latest code updates
        uses: actions/checkout@v4
      - name: create file
        run: echo "hello-wrold" > my-file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-file.txt

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: /root/github-actions-practice

      - name: print artifact
        run: cat /root/github-actions-practice/my-file.txt
