name: secret-message

on:
  push:
    branches:
      - main

jobs:
  secret-message:
    runs-on: ubuntu-latest
    steps: # Line 11: Indented 2 spaces from 'secret-message'
      - name: Read and print secret # Line 12: Indented 2 spaces from 'steps'
        run: echo "The secret is set: true" # Line 13: Indented 2 spaces from the '-'
