name: secret-message

on:
  push:
    branches: [main]
jobs:
  secret-message:
    runs-on: ubuntu-latest
    steps:
      - name: Read and print secret
        run: echo "The secret is set true"

      - name: print secret
        run echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
