name: schedule trigger

on:
  push:
    branches: 
      - main


jobs:
  schedule-trigger:
    runs-on: ubuntu-latest
  
  schedule: 
    - cron: "0 0 * * *" 

  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Print versiot
      run: python --version
