name: schedule trigger

on:
  push:
    branches: 
      - main

  schedule:
    - cron: "0 0 * * *"

jobs:
  schedule-trigger:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Print version
        run: python --version
